services:
  postgres:
    image: postgres:18.1
    container_name: furniture-db
    restart: unless-stopped
    environment:
      # These credentials are only used for local development and testing
      POSTGRES_USER: furniture_crawler
      POSTGRES_PASSWORD: Test@123
      POSTGRES_DB: furniture_crawler
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql
      - ./init:/docker-entrypoint-initdb.d:ro
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U furniture_crawler -d furniture_crawler -q || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  db_data:

